version: "3"
services:

  zookeeper: # this is the config manager
    container_name: zookeeper
    user: root
    hostname: zookeeper
    image: "bitnami/zookeeper:latest"
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - poc

  nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi
    user: root
    depends_on:
      - zookeeper
    volumes:
      - ./configs/database_repository:/opt/nifi/nifi-current/database_repository
      - ./configs/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./configs/content_repository:/opt/nifi/nifi-current/content_repository
      - ./configs/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./configs/state:/opt/nifi/nifi-current/state
      - ./configs/logs:/opt/nifi/nifi-current/logs
      # uncomment two lines below after execute `make nifi-config`
      - ./configs/conf:/opt/nifi/nifi-current/conf
      - ./configs/drivers:/opt/nifi/drivers
    ports:
      - 8443:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      # - NIFI_CLUSTER_IS_NODE=true
      # - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    restart: always
    networks:
      - poc

networks:
  poc:
    driver: bridge
